version: '3'

services:
  db:
    image: mysql:latest
    # environment:
    #   MYSQL_ROOT_PASSWORD: root
    #   MYSQL_DATABASE: image_processor
    #   MYSQL_USER: root


  image_processor:
    build: ./image_processor
    ports:
      - "5000:5000"
